language: go

go:
  - "1.x"

before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - make dep

script:
  - make test
  - make install

after_success:
  - bash <(curl -s https://codecov.io/bash)