[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.2.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.16"

[prune]
  go-tests = true
  unused-packages = true
